apiVersion: v1
kind: ServiceAccount
metadata:
  name: predix-logging-operator
  namespace: services
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: predix-logging-operator
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets", "daemonsets"]
    verbs: ["create", "get", "update", "delete", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "update", "delete", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "create", "delete", "deletecollection"]
  - apiGroups: [""]
    resources:
      [
        "persistentvolumes",
        "persistentvolumeclaims",
        "services",
        "secrets",
        "configmaps",
      ]
    verbs: ["create", "get", "update", "delete", "list"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["create", "get", "deletecollection", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["*"]
  - apiGroups: ["enterprises.upmc.com"]
    resources: ["elasticsearchclusters"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: predix-logging-operator
  namespace: services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: predix-logging-operator
subjects:
  - kind: ServiceAccount
    name: predix-logging-operator
    namespace: services
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: predix-logging-operator
  namespace: services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: predix-logging-operator
    spec:
      containers:
        - name: services
          image: upmcenterprises/elasticsearch-operator:0.2.0
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            httpGet:
              path: /live
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 5
      serviceAccount: predix-logging-operator
